### ISSUE TITLE
Abstract property or method breaks build

### ISSUE THREAD

**Issue by MAX-POLKOVNIK** [MAX-POLKOVNIK/DroidInjector#2]
```
internal abstract class MyFragment : AppCompatDialogFragment
    {
        [View] private Button _myButton;

        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            var view = inflater.Inflate(Resource.Layout.Main, container, false);

            Injector.InjectViews(view);

            return view;
        }

        public abstract string ThisBrokeBuild { get; set; }
        public abstract void ThisBrokeBuildToo();
    }
```

```
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Object reference not set to an instance of an object.
MSBUILD : error : StackTrace:
MSBUILD : error :    at Polkovnik.DroidInjector.Fody.InjectorCallReplacer.Execute()
MSBUILD : error :    at Polkovnik.DroidInjector.Fody.FodyInjector.Execute()
MSBUILD : error :    at Polkovnik.DroidInjector.Fody.ModuleWeaver.Execute()
MSBUILD : error :    at lambda_method(Closure , Object )
MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
MSBUILD : error :    at InnerWeaver.Execute()
MSBUILD : error : Source:
MSBUILD : error : Polkovnik.DroidInjector.Fody
MSBUILD : error : TargetSite:
MSBUILD : error : Void Execute()
MSBUILD : error : 
```

**Comment by MAX-POLKOVNIK** [comment]
Fixed in 0.1.4
