### ISSUE TITLE
Build fails with NullReference Exception when built in Release

### ISSUE THREAD

**Issue by SerjLaren** [MAX-POLKOVNIK/DroidInjector#6]
```csharp
internal class StocktakeStoreViewHolder : Java.Lang.Object
{
    #region - Views -

    [View] private TextView _stocktakeStoreTitle;
    [View] private TextView _stocktakingStoreState;

	/// <param name="view">View.</param>
	private void LoadViews(View view)
	{
        Injector.InjectViews(view);
	}

	#endregion

	/// <summary>
	/// Контекст.
	/// </summary>
	private Activity _context;

	/// <summary>
	/// Initializes a new instance of the <see cref="StocktakeStoreViewHolder"/> class.
	/// </summary>
	private StocktakeStoreViewHolder()
	{
	}

	/// <summary>
	/// Установить информацию в holder.
	/// </summary>
	/// <param name="item">Торговая точка для инвентаризации.</param>
	private void SetInfo(StoreStocktake item)
	{
		switch (item.State) {
		case StocktakingState.AwaitingAcceptance:					
			_stocktakingStoreState.Text = StocktakeResources.stocktaking_awaiting_acceptance;
			break;
		case StocktakingState.InProgress:
			_stocktakingStoreState.Text = StocktakeResources.stocktaking_in_progress;
			break;
		default:
			_stocktakingStoreState.Text = string.Empty;
			break;
		}
		_stocktakeStoreTitle.Text = item.Title;
	}

	/// <summary>
	/// Создать вьюху для элемента адаптера.
	/// </summary>
	/// <param name="convertView">Convert view.</param>
	/// <param name="parent">Parent.</param>
	/// <param name="context">Context.</param>
	/// <param name="item">Элемент адаптера.</param>
	public static View Create(View convertView, ViewGroup parent, Activity context, StoreStocktake item)
	{
		if (context == null)
			return null;

		var view = convertView;
		StocktakeStoreViewHolder itemView;
		if (view == null)
		{
			itemView = new StocktakeStoreViewHolder();
			view = context.LayoutInflater.Inflate(
				Resource.Layout.adapter_stocktake_store_list_element_layout, parent, false);
			itemView.LoadViews (view);
			view.Tag = itemView;
			itemView._context = context;
		}
		else
		{
			itemView = (StocktakeStoreViewHolder)view.Tag;
		}                   

		itemView.SetInfo(item);

		return view;
	}
}
```

Build output
```
21>      Fody/Polkovnik.DroidInjector:   Replace call System.Void Polkovnik.DroidInjector.Injector::InjectViews(Android.Views.View) in System.Void Fraisys.Droid.Sources.Features.Stocktake.StocktakeStoreViewHolder::LoadViews(Android.Views.View)
21>MSBUILD : error : Fody: An unhandled exception occurred:
21>MSBUILD : error : Exception:
21>MSBUILD : error : Object reference not set to an instance of an object.
21>MSBUILD : error : StackTrace:
21>MSBUILD : error :    at Polkovnik.DroidInjector.Fody.InjectorCallReplacer.ReplaceMethodCallInsructions(Instruction callInjectorInstruction, ILProcessor ilProcessor, MethodReference injectionMethod)
21>MSBUILD : error :    at Polkovnik.DroidInjector.Fody.InjectorCallReplacer.Execute()
21>MSBUILD : error :    at Polkovnik.DroidInjector.Fody.FodyInjector.Execute()
21>MSBUILD : error :    at Polkovnik.DroidInjector.Fody.ModuleWeaver.Execute()
21>MSBUILD : error :    at lambda_method(Closure , Object )
21>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
21>MSBUILD : error :    at InnerWeaver.Execute()
21>MSBUILD : error : Source:
21>MSBUILD : error : Polkovnik.DroidInjector.Fody
21>MSBUILD : error : TargetSite:
21>MSBUILD : error : Void ReplaceMethodCallInsructions(Mono.Cecil.Cil.Instruction, Mono.Cecil.Cil.ILProcessor, Mono.Cecil.MethodReference)
21>MSBUILD : error : 
21>    Fody:   Finished Fody 613ms.
```

**Comment by MAX-POLKOVNIK** [comment]
Fixed in 0.2
